INSERT INTO ADMIN (NAME)VALUES ('root');
INSERT INTO THERAPISTS (NAME, SPECIALTY, EMAIL, TLF, DNI) VALUES ('Antonio','Develop','antoniodev@gmail.com',2233466, 4455887 );
INSERT INTO AGENDA (THERAPIST_ID) VALUES (1);
INSERT INTO ACCOUNTS (NAME, PASSWORD, ADMIN_ID) VALUES ('root','passroot',1);
INSERT INTO ACCOUNTS (NAME, PASSWORD, THERAPIST_ID) VALUES ('Antonio','passuser',1);

UPDATE ADMIN SET ACCOUNT_ID = 1 WHERE ID = 1;
UPDATE THERAPISTS SET ACCOUNT_ID = 2 where id = 1; 
UPDATE THERAPISTS SET AGENDA_ID = 1  where id = 1;